### ISSUE TITLE
[HeapViewer] Executable must be ELF fomat

### ISSUE THREAD

**Issue by confilemg** [danigargu/heap-viewer#9]
When running the plugin I get the following message. [HeapViewer] Executable must be ELF fomat

<img width="296" alt="malware-windows_10_pro_x64" src="https://user-images.githubusercontent.com/64265/46910060-0397c480-cf3e-11e8-9e2d-2accaf1dc635.png">

How to handle this?

**Comment by danigargu** [comment]
Hi! what type of executable are you debugging?

**Comment by confilemg** [comment]
I debug a PE file-------- Originalnachricht --------Betreff: Re: [danigargu/heap-viewer] [HeapViewer] Executable must be ELF fomat (#9)Von: Daniel García An: danigargu/heap-viewer Cc: Confilemg ,Author Hi! what type of executable are you debugging?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/danigargu/heap-viewer","title":"danigargu/heap-viewer","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/danigargu/heap-viewer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@danigargu in #9: Hi! what type of executable are you debugging?"}],"action":{"name":"View Issue","url":"https://github.com/danigargu/heap-viewer/issues/9#issuecomment-429775130"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/danigargu/heap-viewer/issues/9#issuecomment-429775130",
"url": "https://github.com/danigargu/heap-viewer/issues/9#issuecomment-429775130",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [danigargu/heap-viewer] [HeapViewer] Executable must be ELF fomat (#9)",
"sections": [
{
"text": "",
"activityTitle": "**Daniel García**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@danigargu",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"danigargu/heap-viewer\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"danigargu/heap-viewer\",\n\"issueId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/danigargu/heap-viewer/issues/9#issuecomment-429775130"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 392909939\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by danigargu** [comment]
Sorry! The plugin only works for linux (ELF files & glibc heap)
In the future I would like to support the Windows heap

**Comment by theboy181** [comment]
Any work on Windows ? was looking forward to this, and got the same error.
